In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

import yfinance as yf
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
from pprint import pprint

from datetime import datetime
from tqdm import tqdm

In [2]:
# S&P100 전체 종목 이름, 심볼, 섹터 가져오기
res = requests.get(url = 'https://en.wikipedia.org/wiki/S%26P_100',
                    headers={'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) \
                    AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'})

df_symbol = pd.read_html(res.text)[2]
df_symbol.to_csv('../data/stock_data.csv', index=False)

df_symbol.head()

  Symbol                 Name                  Sector
0   AAPL           Apple Inc.  Information Technology
1   ABBV               AbbVie             Health Care
2    ABT  Abbott Laboratories             Health Care
3    ACN            Accenture  Information Technology
4   ADBE           Adobe Inc.  Information Technology

In [3]:
# 이벤트 데이터 생성
df_stock = pd.read_csv('../data/df_cond1_tidy.csv')
cond = df_stock['Symbol'].isin(df_symbol.Symbol.tolist())
df_cond1 = df_stock[cond]
df_cond1.head()

df_merged = df_cond1.merge(df_symbol, how='left', on='Symbol')
df_event = df_merged[['Date', 'Symbol', 'Name', 'Sector']]
df_event.to_csv('../data/event_data.csv', index=False)
df_event.head()

         Date Symbol        Name                  Sector
0  2025-04-09   AAPL  Apple Inc.  Information Technology
1  2024-03-15   ADBE  Adobe Inc.  Information Technology
2  2024-06-14   ADBE  Adobe Inc.  Information Technology
3  2024-12-12   ADBE  Adobe Inc.  Information Technology
4  2025-03-13   ADBE  Adobe Inc.  Information Technology

In [4]:
# 테스트를 위한 이벤트 조사
np.random.seed(252)
df_event.sample(2)

          Date Symbol         Name                  Sector
75  2024-10-24   TSLA  Tesla, Inc.  Consumer Discretionary
61  2024-02-08   PYPL       PayPal              Financials

In [5]:
ticker = yf.Ticker("TSLA")

news_list = ticker.news
target_date = datetime(2024, 10, 24).date()

# pprint(news_list)

len(ticker.get_news(count=100))
### ---> 최근 10개까지만 가능한가?
### ---> 공식 문서에 명시되어 있지 않지만 그래 보임 ㅜㅜ

10

In [6]:
# 다른 접근법
from unittest import result
from GoogleNews import GoogleNews
googlenews = GoogleNews(lang='en')
googlenews.get_news('TESLA')
googlenews.set_time_range(start='2024-10-24', end='2024-10-24')



pd.DataFrame(googlenews.result()).head()
# 역시 최신 기사만 불러온다. 이러면 안됨.

,title,desc,date,datetime,link,img,media,site,reporter
0,Tesla’s Full-Self Driving Software Is A Mess. ...,None,17 hours ago,2025-09-23 20:23:27.902019,https://news.google.com/read/CBMitgFBVV95cUxPW...,https://news.google.com/api/attachments/CC8iK0...,Forbes,None,By Alan Ohnsman
1,Tesla stock jumps to new 2025 closing high as ...,None,22 hours ago,2025-09-23 15:23:27.902230,https://news.google.com/read/CBMirgFBVV95cUxOQ...,https://news.google.com/api/attachments/CC8iL0...,Yahoo Finance,None,By Pras Subramanian
2,Tesla Stock Has Soared 27% This Month And This...,None,8 hours ago,2025-09-24 05:23:27.902405,https://news.google.com/read/CBMinwFBVV95cUxPN...,https://news.google.com/api/attachments/CC8iL0...,Investor's Business Daily,None,By Kit Norton
3,Why Tesla Stock Is Rising Again and Microsoft ...,None,14 hours ago,2025-09-23 23:23:27.902579,https://news.google.com/read/CBMigAFBVV95cUxON...,https://news.google.com/api/attachments/CC8iK0...,Barron's,None,By Jack Denton
4,A Hacker Decodes and Reveals More Information ...,None,Yesterday,2025-09-23 13:23:27.902746,https://news.google.com/read/CBMijwFBVV95cUxQc...,https://news.google.com/api/attachments/CC8iJ0...,MotorTrend,None,By Justin Banner

In [8]:
# 다른 접근법 Gnews
from gnews import GNews
googlenews = GNews(
    language='en',
    country='US'
)

googlenews.start_date = (2024, 10, 23)
googlenews.end_date = (2024, 10, 24)

# results = pd.DataFrame(googlenews.get_news('TESLA'))
# results

# 질 불러와진다. 이대로 사용하자.

In [ ]:
# C 스크립트 실행 후

df_processed = pd.read_csv('../data/articles/csv/filtered_news_20250924_043743.csv')
df_processed

,event_date,search_date,symbol,title,description,published_date,url,publisher_title,publisher_href,parsed_published_date,is_target_date
0,2024-03-15T00:00:00,2024-03-14,ADBE,Adobe shares slip 10% on soft sales forecast -...,Adobe shares slip 10% on soft sales forecast ...,"Thu, 14 Mar 2024 07:00:00 GMT",https://news.google.com/rss/articles/CBMie0FVX...,CNBC,https://www.cnbc.com,2024-03-14T07:00:00+00:00,True
1,2024-03-15T00:00:00,2024-03-14,ADBE,ADBE Earnings: Adobe Q1 2024 revenue and profi...,ADBE Earnings: Adobe Q1 2024 revenue and profi...,"Thu, 14 Mar 2024 07:00:00 GMT",https://news.google.com/rss/articles/CBMilgFBV...,AlphaStreet,https://news.alphastreet.com,2024-03-14T07:00:00+00:00,True
2,2024-03-15T00:00:00,2024-03-14,ADBE,Adobe Approves $25 Bln Stock Buyback - Nasdaq,Adobe Approves $25 Bln Stock Buyback Nasdaq,"Thu, 14 Mar 2024 07:00:00 GMT",https://news.google.com/rss/articles/CBMid0FVX...,Nasdaq,https://www.nasdaq.com,2024-03-14T07:00:00+00:00,True
3,2024-03-15T00:00:00,2024-03-14,ADBE,What You Need To Know Ahead of Adobe's Earning...,What You Need To Know Ahead of Adobe's Earning...,"Thu, 14 Mar 2024 07:00:00 GMT",https://news.google.com/rss/articles/CBMiekFVX...,Investopedia,https://www.investopedia.com,2024-03-14T07:00:00+00:00,True
4,2024-03-15T00:00:00,2024-03-14,ADBE,Adobe forecasts downbeat second-quarter revenu...,Adobe forecasts downbeat second-quarter revenu...,"Thu, 14 Mar 2024 07:00:00 GMT",https://news.google.com/rss/articles/CBMimgFBV...,Reuters,https://www.reuters.com,2024-03-14T07:00:00+00:00,True
...,...,...,...,...,...,...,...,...,...,...,...
1655,2025-01-30T00:00:00,2025-01-29,UPS,APUS IPO News - Inflammation biotech Apimeds P...,APUS IPO News - Inflammation biotech Apimeds P...,"Wed, 29 Jan 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMizgFBV...,renaissancecapital.com,https://www.renaissancecapital.com,2025-01-29T08:00:00+00:00,True
1656,2025-01-30T00:00:00,2025-01-29,UPS,"AEG UPS WILKES, HILL IN INTERNATIONAL REORG - ...","AEG UPS WILKES, HILL IN INTERNATIONAL REORG H...","Wed, 29 Jan 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMikwFBV...,Hits Daily Double,https://www.hitsdailydouble.com,2025-01-29T08:00:00+00:00,True
1657,2025-01-30T00:00:00,2025-01-29,UPS,Cram Motorsport and US Racing grow 2025 Formul...,Cram Motorsport and US Racing grow 2025 Formul...,"Wed, 29 Jan 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMilAFBV...,Formula Scout,https://formulascout.com,2025-01-29T08:00:00+00:00,True
1658,2024-11-06T00:00:00,2024-11-05,WFC,First Wells Fargo contract negotiations set to...,First Wells Fargo contract negotiations set to...,"Tue, 05 Nov 2024 08:00:00 GMT",https://news.google.com/rss/articles/CBMijgFBV...,Yahoo Finance,https://finance.yahoo.com,2024-11-05T08:00:00+00:00,True
1659,2024-11-06T00:00:00,2024-11-05,WFC,"Sony WF-C700N review: comfort, ANC and sensati...","Sony WF-C700N review: comfort, ANC and sensati...","Tue, 05 Nov 2024 08:00:00 GMT",https://news.google.com/rss/articles/CBMiWkFVX...,What Hi-Fi?,https://www.whathifi.com,2024-11-05T08:00:00+00:00,True

In [11]:
df_event

           Date Symbol                   Name                  Sector
0    2025-04-09   AAPL             Apple Inc.  Information Technology
1    2024-03-15   ADBE             Adobe Inc.  Information Technology
2    2024-06-14   ADBE             Adobe Inc.  Information Technology
3    2024-12-12   ADBE             Adobe Inc.  Information Technology
4    2025-03-13   ADBE             Adobe Inc.  Information Technology
..          ...    ...                    ...                     ...
155  2025-08-15    UNH     UnitedHealth Group             Health Care
156  2024-07-23    UPS  United Parcel Service             Industrials
157  2025-01-30    UPS  United Parcel Service             Industrials
158  2025-07-29    UPS  United Parcel Service             Industrials
159  2024-11-06    WFC            Wells Fargo              Financials

[160 rows x 4 columns]

In [ ]:
# input data 정리
df = pd.read_csv('../data/articles/csv/news_with_market_cap_20250924_135112.csv')
cond1 = (df['search_date'] == '2024-12-11')
df_temp1 = df[cond1]
df_temp1

,event_date,search_date,symbol,title,description,published_date,url,publisher_title,publisher_href,parsed_published_date,is_target_date,market_cap
9,2024-12-12T00:00:00,2024-12-11,ADBE,Adobe’s (NASDAQ:ADBE) Q4 Sales Beat Estimates ...,Adobe’s (NASDAQ:ADBE) Q4 Sales Beat Estimates ...,"Wed, 11 Dec 2024 08:00:00 GMT",https://news.google.com/rss/articles/CBMifEFVX...,Yahoo Finance,https://finance.yahoo.com,2024-12-11T08:00:00+00:00,True,2.332803e+11
10,2024-12-12T00:00:00,2024-12-11,ADBE,Adobe Stock Drops as Revenue Forecast Disappoi...,Adobe Stock Drops as Revenue Forecast Disappoi...,"Wed, 11 Dec 2024 08:00:00 GMT",https://news.google.com/rss/articles/CBMib0FVX...,Investopedia,https://www.investopedia.com,2024-12-11T08:00:00+00:00,True,2.332803e+11
11,2024-12-12T00:00:00,2024-12-11,ADBE,Adobe Reports Record Q4 and Fiscal 2024 Revenu...,Adobe Reports Record Q4 and Fiscal 2024 Revenu...,"Wed, 11 Dec 2024 08:00:00 GMT",https://news.google.com/rss/articles/CBMipwFBV...,Business Wire,https://www.businesswire.com,2024-12-11T08:00:00+00:00,True,2.332803e+11
12,2024-12-12T00:00:00,2024-12-11,ADBE,Adobe (ADBE) Results Seen as ‘Make-or-Break’ t...,Adobe (ADBE) Results Seen as ‘Make-or-Break’ t...,"Wed, 11 Dec 2024 08:00:00 GMT",https://news.google.com/rss/articles/CBMirwFBV...,Bloomberg,https://www.bloomberg.com,2024-12-11T08:00:00+00:00,True,2.332803e+11

In [21]:
df_temp2  =df_temp1[['search_date', 'symbol','description', 'title', 'market_cap']]
df_temp2.to_dict()

{'search_date': {9: '2024-12-11',
  10: '2024-12-11',
  11: '2024-12-11',
  12: '2024-12-11'},
 'symbol': {9: 'ADBE', 10: 'ADBE', 11: 'ADBE', 12: 'ADBE'},
 'description': {9: 'Adobe’s (NASDAQ:ADBE) Q4 Sales Beat Estimates But Full-Year Sales Guidance Misses Expectations Significantly  Yahoo Finance',
  10: 'Adobe Stock Drops as Revenue Forecast Disappoints  Investopedia',
  11: 'Adobe Reports Record Q4 and Fiscal 2024 Revenue  Business Wire',
  12: 'Adobe (ADBE) Results Seen as ‘Make-or-Break’ to Prove AI Credentials  Bloomberg'},
 'title': {9: 'Adobe’s (NASDAQ:ADBE) Q4 Sales Beat Estimates But Full-Year Sales Guidance Misses Expectations Significantly - Yahoo Finance',
  10: 'Adobe Stock Drops as Revenue Forecast Disappoints - Investopedia',
  11: 'Adobe Reports Record Q4 and Fiscal 2024 Revenue - Business Wire',
  12: 'Adobe (ADBE) Results Seen as ‘Make-or-Break’ to Prove AI Credentials - Bloomberg'},
 'market_cap': {9: 233280302893.0664,
  10: 233280302893.0664,
  11: 233280302893.0664,
  12: 233280302893.0664}}

In [4]:
import pandas as pd
import yfinance as yf

ticker = yf.Ticker('005930.KS')
df = ticker.history(period='1mo')
df.reset_index().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          17 non-null     datetime64[ns, Asia/Seoul]
 1   Open          17 non-null     float64
 2   High          17 non-null     float64
 3   Low           17 non-null     float64
 4   Close         17 non-null     float64
 5   Volume        17 non-null     int64
 6   Dividends     17 non-null     float64
 7   Stock Splits  17 non-null     float64
dtypes: datetime64[ns, Asia/Seoul](1), float64(6), int64(1)
memory usage: 1.2 KB

In [46]:
# 코드 검증
import pandas as pd
import yfinance as yf
import numpy as np
from datetime import datetime
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

# -----------------------------
# 1. 예측 결과 불러오기
# -----------------------------
df_predict = pd.read_csv('../data/answer/prediction_results.csv')

df_predict['search_date'] = pd.to_datetime(df_predict['search_date'])
df_predict['prediction_date'] = pd.to_datetime(df_predict['prediction_date'])

# 예측 기간 계산 (days_diff)
df_predict['days_diff'] = (df_predict['prediction_date'] - df_predict['search_date']).dt.days

# 거래일 오프셋 설정 (미국 연방 공휴일 반영)
us_bd = CustomBusinessDay(calendar=USFederalHolidayCalendar())

# 거래일 기준으로 prediction_date 보정
df_predict['prediction_date_adj'] = df_predict.apply(
    lambda row: row['search_date'] + us_bd * row['days_diff'], axis=1
)

# prediction_date_adj를 datetime으로 변환
df_predict['prediction_date_adj'] = pd.to_datetime(df_predict['prediction_date_adj'])

# 보정 여부 및 보정 일수 계산
df_predict['보정여부'] = (df_predict['prediction_date_adj'] - df_predict['prediction_date']).dt.days
df_predict['보정여부'] = df_predict['보정여부'].fillna(0).astype(int)

# 보정 후 prediction_date 사용
df_predict['prediction_date'] = df_predict['prediction_date_adj']
df_predict.drop(columns=['prediction_date_adj'], inplace=True)

# decision을 수치로 매핑
df_predict['predicted_sign'] = df_predict['decision'].map({'buy': 1, 'sell': -1})
df_predict

,symbol,search_date,prediction_date,model_type,model_name,decision,confidence,reason,days_diff,보정여부,predicted_sign
0,ADBE,2024-03-14,2024-03-15,expert,gpt-5,sell,68.0,Soft Q2 revenue guide drove a 10% drop; likely...,1,0,-1.0
1,ADBE,2024-03-14,2024-03-19,expert,gpt-5,sell,62.0,Post-earnings digestion and potential downgrad...,3,2,-1.0
2,ADBE,2024-03-14,2024-03-25,expert,gpt-5,buy,56.0,Selling pressure may fade; $25B buyback and ea...,7,4,1.0
3,ADBE,2024-03-14,2024-04-04,expert,gpt-5,buy,60.0,Estimates likely reset; stabilization from rep...,15,6,1.0
4,ADBE,2024-03-14,2024-04-25,expert,gpt-5,buy,66.0,Strong fundamentals plus large buyback could d...,30,12,1.0
5,ADBE,2024-03-14,2024-03-15,crowd_1,gpt-5-nano,sell,75.0,Soft Q2 guidance after Q1 beat; about 10% intr...,1,0,-1.0
6,ADBE,2024-03-14,2024-03-19,crowd_1,gpt-5-nano,sell,65.0,Momentum likely to persist with cautious outlo...,3,2,-1.0
7,ADBE,2024-03-14,2024-03-25,crowd_1,gpt-5-nano,sell,50.0,Signals are mixed; potential short-term reboun...,7,4,-1.0
8,ADBE,2024-03-14,2024-04-04,crowd_1,gpt-5-nano,buy,60.0,Negative news may be priced in; buyback and br...,15,6,1.0
9,ADBE,2024-03-14,2024-04-25,crowd_1,gpt-5-nano,buy,70.0,With more time to digest results and ongoing b...,30,12,1.0
10,ADBE,2024-03-14,2024-03-15,crowd_2,gpt-5-nano,sell,75.0,Adobe warned of soft Q2 revenue; stock fell ~1...,1,0,-1.0
11,ADBE,2024-03-14,2024-03-19,crowd_2,gpt-5-nano,sell,70.0,Sustained negative guidance and cautious senti...,3,2,-1.0
12,ADBE,2024-03-14,2024-03-25,crowd_2,gpt-5-nano,buy,50.0,Potential stabilization from the sizable buyba...,7,4,1.0
13,ADBE,2024-03-14,2024-04-04,crowd_2,gpt-5-nano,buy,60.0,Medium-term value from capital return and impr...,15,6,1.0
14,ADBE,2024-03-14,2024-04-25,crowd_2,gpt-5-nano,buy,65.0,Longer horizon may benefit from the buyback an...,30,12,1.0
15,ADBE,2024-03-14,2024-03-15,crowd_3,gpt-5-nano,sell,78.0,Immediate negative catalyst: soft forecast and...,1,0,-1.0
16,ADBE,2024-03-14,2024-03-19,crowd_3,gpt-5-nano,sell,65.0,Guidance disappointment suggests continued sho...,3,2,-1.0
17,ADBE,2024-03-14,2024-03-25,crowd_3,gpt-5-nano,sell,55.0,Overhang from weak guidance persists; risk-rew...,7,4,-1.0
18,ADBE,2024-03-14,2024-04-04,crowd_3,gpt-5-nano,buy,60.0,Stock likely oversold; durable fundamentals an...,15,6,1.0
19,ADBE,2024-03-14,2024-04-25,crowd_3,gpt-5-nano,buy,72.0,Valuation may be attractive after the pullback...,30,12,1.0
20,ADBE,2024-03-14,2024-03-15,crowd_average,crowd_models,NaN,76.0,Average confidence across 3 crowd models,1,0,NaN
21,ADBE,2024-03-14,2024-03-19,crowd_average,crowd_models,NaN,66.7,Average confidence across 3 crowd models,3,2,NaN
22,ADBE,2024-03-14,2024-03-25,crowd_average,crowd_models,NaN,51.7,Average confidence across 3 crowd models,7,4,NaN
23,ADBE,2024-03-14,2024-04-04,crowd_average,crowd_models,NaN,60.0,Average confidence across 3 crowd models,15,6,NaN
24,ADBE,2024-03-14,2024-04-25,crowd_average,crowd_models,NaN,69.0,Average confidence across 3 crowd models,30,12,NaN

In [41]:

# -----------------------------
# 2. 실제 주가 데이터 수집 (모든 심볼)
# -----------------------------
def get_price_data(symbol: str, start_date, end_date):
    """심볼별 주가 데이터 조회"""
    try:
        ticker = yf.Ticker(symbol)
        # 충분한 기간의 데이터 확보 (시작일 7일 전부터 종료일 7일 후까지)
        start_adj = pd.to_datetime(start_date) - pd.Timedelta(days=7)
        end_adj = pd.to_datetime(end_date) + pd.Timedelta(days=7)
        df_symbol = ticker.history(start=start_adj, end=end_adj)

        if len(df_symbol) == 0:
            print(f"경고: {symbol} 데이터 없음 ({start_date} ~ {end_date})")
            return pd.DataFrame()

        df_symbol = df_symbol[['Close']].reset_index()
        df_symbol['Date'] = pd.to_datetime(df_symbol['Date']).dt.tz_localize(None)
        df_symbol['symbol'] = symbol
        return df_symbol
    except Exception as e:
        print(f"오류: {symbol} 조회 실패 - {e}")
        return pd.DataFrame()

# 모든 심볼의 주가 데이터 수집
symbols = df_predict['symbol'].unique()
min_date = df_predict['search_date'].min()
max_date = df_predict['prediction_date'].max()

print(f"주가 데이터 수집 중: {len(symbols)}개 심볼 ({min_date.date()} ~ {max_date.date()})")

주가 데이터 수집 중: 1개 심볼 (2024-03-14 ~ 2024-04-25)

In [42]:
price_data_list = []
for symbol in symbols:
    df_symbol = get_price_data(symbol, min_date, max_date)
    if len(df_symbol) > 0:
        price_data_list.append(df_symbol)
    print(f"  - {symbol}: {len(df_symbol)}개 데이터")

if len(price_data_list) == 0:
    raise ValueError("주가 데이터를 조회할 수 없습니다.")

df_all_prices = pd.concat(price_data_list, ignore_index=True)
df_all_prices

  - ADBE: 39개 데이터

         Date       Close symbol
0  2024-03-07  556.039978   ADBE
1  2024-03-08  551.690002   ADBE
2  2024-03-11  560.419983   ADBE
3  2024-03-12  579.140015   ADBE
4  2024-03-13  573.549988   ADBE
5  2024-03-14  570.450012   ADBE
6  2024-03-15  492.459991   ADBE
7  2024-03-18  513.859985   ADBE
8  2024-03-19  521.190002   ADBE
9  2024-03-20  519.140015   ADBE
10 2024-03-21  511.250000   ADBE
11 2024-03-22  499.519989   ADBE
12 2024-03-25  507.230011   ADBE
13 2024-03-26  507.600006   ADBE
14 2024-03-27  504.399994   ADBE
15 2024-03-28  504.600006   ADBE
16 2024-04-01  502.089996   ADBE
17 2024-04-02  499.209991   ADBE
18 2024-04-03  497.010010   ADBE
19 2024-04-04  487.109985   ADBE
20 2024-04-05  485.119995   ADBE
21 2024-04-08  484.279999   ADBE
22 2024-04-09  492.549988   ADBE
23 2024-04-10  487.220001   ADBE
24 2024-04-11  484.279999   ADBE
25 2024-04-12  474.089996   ADBE
26 2024-04-15  470.100006   ADBE
27 2024-04-16  476.220001   ADBE
28 2024-04-17  474.450012   ADBE
29 2024-04-18  473.179993   ADBE
30 2024-04-19  465.019989   ADBE
31 2024-04-22  466.890015   ADBE
32 2024-04-23  472.899994   ADBE
33 2024-04-24  477.119995   ADBE
34 2024-04-25  473.440002   ADBE
35 2024-04-26  477.559998   ADBE
36 2024-04-29  473.070007   ADBE
37 2024-04-30  462.829987   ADBE
38 2024-05-01  469.390015   ADBE

In [44]:

# -----------------------------
# 3. search_date / prediction_date 가격 매칭 (보정된 날짜 기준)
# -----------------------------
# search_date 가격 매칭
df_search = df_all_prices[['symbol', 'Date', 'Close']].rename(
    columns={'Date': 'search_date', 'Close': 'Close_search'}
)
df_merge = df_predict.merge(df_search, on=['symbol', 'search_date'], how='left')

# prediction_date 가격 매칭 (보정된 날짜)
df_pred = df_all_prices[['symbol', 'Date', 'Close']].rename(
    columns={'Date': 'prediction_date', 'Close': 'Close_pred'}
)
df_merge = df_merge.merge(df_pred, on=['symbol', 'prediction_date'], how='left')
df_merge

,symbol,search_date,prediction_date,model_type,model_name,decision,confidence,reason,days_diff,보정여부,predicted_sign,Close_search,Close_pred
0,ADBE,2024-03-14,2024-03-15,expert,gpt-5,sell,68.0,Soft Q2 revenue guide drove a 10% drop; likely...,1,0,-1.0,570.450012,492.459991
1,ADBE,2024-03-14,2024-03-19,expert,gpt-5,sell,62.0,Post-earnings digestion and potential downgrad...,3,2,-1.0,570.450012,521.190002
2,ADBE,2024-03-14,2024-03-25,expert,gpt-5,buy,56.0,Selling pressure may fade; $25B buyback and ea...,7,4,1.0,570.450012,507.230011
3,ADBE,2024-03-14,2024-04-04,expert,gpt-5,buy,60.0,Estimates likely reset; stabilization from rep...,15,6,1.0,570.450012,487.109985
4,ADBE,2024-03-14,2024-04-25,expert,gpt-5,buy,66.0,Strong fundamentals plus large buyback could d...,30,12,1.0,570.450012,473.440002
5,ADBE,2024-03-14,2024-03-15,crowd_1,gpt-5-nano,sell,75.0,Soft Q2 guidance after Q1 beat; about 10% intr...,1,0,-1.0,570.450012,492.459991
6,ADBE,2024-03-14,2024-03-19,crowd_1,gpt-5-nano,sell,65.0,Momentum likely to persist with cautious outlo...,3,2,-1.0,570.450012,521.190002
7,ADBE,2024-03-14,2024-03-25,crowd_1,gpt-5-nano,sell,50.0,Signals are mixed; potential short-term reboun...,7,4,-1.0,570.450012,507.230011
8,ADBE,2024-03-14,2024-04-04,crowd_1,gpt-5-nano,buy,60.0,Negative news may be priced in; buyback and br...,15,6,1.0,570.450012,487.109985
9,ADBE,2024-03-14,2024-04-25,crowd_1,gpt-5-nano,buy,70.0,With more time to digest results and ongoing b...,30,12,1.0,570.450012,473.440002
10,ADBE,2024-03-14,2024-03-15,crowd_2,gpt-5-nano,sell,75.0,Adobe warned of soft Q2 revenue; stock fell ~1...,1,0,-1.0,570.450012,492.459991
11,ADBE,2024-03-14,2024-03-19,crowd_2,gpt-5-nano,sell,70.0,Sustained negative guidance and cautious senti...,3,2,-1.0,570.450012,521.190002
12,ADBE,2024-03-14,2024-03-25,crowd_2,gpt-5-nano,buy,50.0,Potential stabilization from the sizable buyba...,7,4,1.0,570.450012,507.230011
13,ADBE,2024-03-14,2024-04-04,crowd_2,gpt-5-nano,buy,60.0,Medium-term value from capital return and impr...,15,6,1.0,570.450012,487.109985
14,ADBE,2024-03-14,2024-04-25,crowd_2,gpt-5-nano,buy,65.0,Longer horizon may benefit from the buyback an...,30,12,1.0,570.450012,473.440002
15,ADBE,2024-03-14,2024-03-15,crowd_3,gpt-5-nano,sell,78.0,Immediate negative catalyst: soft forecast and...,1,0,-1.0,570.450012,492.459991
16,ADBE,2024-03-14,2024-03-19,crowd_3,gpt-5-nano,sell,65.0,Guidance disappointment suggests continued sho...,3,2,-1.0,570.450012,521.190002
17,ADBE,2024-03-14,2024-03-25,crowd_3,gpt-5-nano,sell,55.0,Overhang from weak guidance persists; risk-rew...,7,4,-1.0,570.450012,507.230011
18,ADBE,2024-03-14,2024-04-04,crowd_3,gpt-5-nano,buy,60.0,Stock likely oversold; durable fundamentals an...,15,6,1.0,570.450012,487.109985
19,ADBE,2024-03-14,2024-04-25,crowd_3,gpt-5-nano,buy,72.0,Valuation may be attractive after the pullback...,30,12,1.0,570.450012,473.440002
20,ADBE,2024-03-14,2024-03-15,crowd_average,crowd_models,NaN,76.0,Average confidence across 3 crowd models,1,0,NaN,570.450012,492.459991
21,ADBE,2024-03-14,2024-03-19,crowd_average,crowd_models,NaN,66.7,Average confidence across 3 crowd models,3,2,NaN,570.450012,521.190002
22,ADBE,2024-03-14,2024-03-25,crowd_average,crowd_models,NaN,51.7,Average confidence across 3 crowd models,7,4,NaN,570.450012,507.230011
23,ADBE,2024-03-14,2024-04-04,crowd_average,crowd_models,NaN,60.0,Average confidence across 3 crowd models,15,6,NaN,570.450012,487.109985
24,ADBE,2024-03-14,2024-04-25,crowd_average,crowd_models,NaN,69.0,Average confidence across 3 crowd models,30,12,NaN,570.450012,473.440002

In [48]:

# -----------------------------
# 4. NaN 처리 및 데이터 검증
# -----------------------------
# 가격 매칭 실패한 행 확인
missing_search = df_merge['Close_search'].isna().sum()
missing_pred = df_merge['Close_pred'].isna().sum()

print(missing_search)
print(missing_pred)


if missing_search > 0:
    print(f"경고: search_date 가격 매칭 실패 {missing_search}건")
if missing_pred > 0:
    print(f"경고: prediction_date 가격 매칭 실패 {missing_pred}건")

# NaN이 있는 행 제거
df_merge = df_merge.dropna(subset=['Close_search', 'Close_pred'])
print(f"유효한 데이터: {len(df_merge)}건")

0
0
유효한 데이터: 25건

In [50]:
# -----------------------------
# 5. 실제 등락 계산
# -----------------------------
df_merge['price_change'] = df_merge['Close_pred'] - df_merge['Close_search']
df_merge['actual_sign'] = np.sign(df_merge['price_change'])

# -----------------------------
# 6. 예측 일치 여부 & 가중 점수
# -----------------------------
df_merge['correct'] = np.where(df_merge['predicted_sign'] == df_merge['actual_sign'], 1, 0)
df_merge['weighted_score'] = np.where(df_merge['correct'] == 1, df_merge['confidence'], -df_merge['confidence'])

df_merge

,symbol,search_date,prediction_date,model_type,model_name,decision,confidence,reason,days_diff,보정여부,predicted_sign,Close_search,Close_pred,price_change,actual_sign,correct,weighted_score
0,ADBE,2024-03-14,2024-03-15,expert,gpt-5,sell,68.0,Soft Q2 revenue guide drove a 10% drop; likely...,1,0,-1.0,570.450012,492.459991,-77.990021,-1.0,1,68.0
1,ADBE,2024-03-14,2024-03-19,expert,gpt-5,sell,62.0,Post-earnings digestion and potential downgrad...,3,2,-1.0,570.450012,521.190002,-49.260010,-1.0,1,62.0
2,ADBE,2024-03-14,2024-03-25,expert,gpt-5,buy,56.0,Selling pressure may fade; $25B buyback and ea...,7,4,1.0,570.450012,507.230011,-63.220001,-1.0,0,-56.0
3,ADBE,2024-03-14,2024-04-04,expert,gpt-5,buy,60.0,Estimates likely reset; stabilization from rep...,15,6,1.0,570.450012,487.109985,-83.340027,-1.0,0,-60.0
4,ADBE,2024-03-14,2024-04-25,expert,gpt-5,buy,66.0,Strong fundamentals plus large buyback could d...,30,12,1.0,570.450012,473.440002,-97.010010,-1.0,0,-66.0
5,ADBE,2024-03-14,2024-03-15,crowd_1,gpt-5-nano,sell,75.0,Soft Q2 guidance after Q1 beat; about 10% intr...,1,0,-1.0,570.450012,492.459991,-77.990021,-1.0,1,75.0
6,ADBE,2024-03-14,2024-03-19,crowd_1,gpt-5-nano,sell,65.0,Momentum likely to persist with cautious outlo...,3,2,-1.0,570.450012,521.190002,-49.260010,-1.0,1,65.0
7,ADBE,2024-03-14,2024-03-25,crowd_1,gpt-5-nano,sell,50.0,Signals are mixed; potential short-term reboun...,7,4,-1.0,570.450012,507.230011,-63.220001,-1.0,1,50.0
8,ADBE,2024-03-14,2024-04-04,crowd_1,gpt-5-nano,buy,60.0,Negative news may be priced in; buyback and br...,15,6,1.0,570.450012,487.109985,-83.340027,-1.0,0,-60.0
9,ADBE,2024-03-14,2024-04-25,crowd_1,gpt-5-nano,buy,70.0,With more time to digest results and ongoing b...,30,12,1.0,570.450012,473.440002,-97.010010,-1.0,0,-70.0
10,ADBE,2024-03-14,2024-03-15,crowd_2,gpt-5-nano,sell,75.0,Adobe warned of soft Q2 revenue; stock fell ~1...,1,0,-1.0,570.450012,492.459991,-77.990021,-1.0,1,75.0
11,ADBE,2024-03-14,2024-03-19,crowd_2,gpt-5-nano,sell,70.0,Sustained negative guidance and cautious senti...,3,2,-1.0,570.450012,521.190002,-49.260010,-1.0,1,70.0
12,ADBE,2024-03-14,2024-03-25,crowd_2,gpt-5-nano,buy,50.0,Potential stabilization from the sizable buyba...,7,4,1.0,570.450012,507.230011,-63.220001,-1.0,0,-50.0
13,ADBE,2024-03-14,2024-04-04,crowd_2,gpt-5-nano,buy,60.0,Medium-term value from capital return and impr...,15,6,1.0,570.450012,487.109985,-83.340027,-1.0,0,-60.0
14,ADBE,2024-03-14,2024-04-25,crowd_2,gpt-5-nano,buy,65.0,Longer horizon may benefit from the buyback an...,30,12,1.0,570.450012,473.440002,-97.010010,-1.0,0,-65.0
15,ADBE,2024-03-14,2024-03-15,crowd_3,gpt-5-nano,sell,78.0,Immediate negative catalyst: soft forecast and...,1,0,-1.0,570.450012,492.459991,-77.990021,-1.0,1,78.0
16,ADBE,2024-03-14,2024-03-19,crowd_3,gpt-5-nano,sell,65.0,Guidance disappointment suggests continued sho...,3,2,-1.0,570.450012,521.190002,-49.260010,-1.0,1,65.0
17,ADBE,2024-03-14,2024-03-25,crowd_3,gpt-5-nano,sell,55.0,Overhang from weak guidance persists; risk-rew...,7,4,-1.0,570.450012,507.230011,-63.220001,-1.0,1,55.0
18,ADBE,2024-03-14,2024-04-04,crowd_3,gpt-5-nano,buy,60.0,Stock likely oversold; durable fundamentals an...,15,6,1.0,570.450012,487.109985,-83.340027,-1.0,0,-60.0
19,ADBE,2024-03-14,2024-04-25,crowd_3,gpt-5-nano,buy,72.0,Valuation may be attractive after the pullback...,30,12,1.0,570.450012,473.440002,-97.010010,-1.0,0,-72.0
20,ADBE,2024-03-14,2024-03-15,crowd_average,crowd_models,NaN,76.0,Average confidence across 3 crowd models,1,0,NaN,570.450012,492.459991,-77.990021,-1.0,0,-76.0
21,ADBE,2024-03-14,2024-03-19,crowd_average,crowd_models,NaN,66.7,Average confidence across 3 crowd models,3,2,NaN,570.450012,521.190002,-49.260010,-1.0,0,-66.7
22,ADBE,2024-03-14,2024-03-25,crowd_average,crowd_models,NaN,51.7,Average confidence across 3 crowd models,7,4,NaN,570.450012,507.230011,-63.220001,-1.0,0,-51.7
23,ADBE,2024-03-14,2024-04-04,crowd_average,crowd_models,NaN,60.0,Average confidence across 3 crowd models,15,6,NaN,570.450012,487.109985,-83.340027,-1.0,0,-60.0
24,ADBE,2024-03-14,2024-04-25,crowd_average,crowd_models,NaN,69.0,Average confidence across 3 crowd models,30,12,NaN,570.450012,473.440002,-97.010010,-1.0,0,-69.0

In [51]:
# -----------------------------
# 7. Crowd 집단 통합 (투표 방식)
# -----------------------------
def aggregate_crowd_predictions(df):
    crowd_df = df[df['model_type'].str.startswith('crowd', na=False)].copy()
    if len(crowd_df) == 0:
        return pd.DataFrame()

    grouped = crowd_df.groupby(['symbol', 'search_date', 'prediction_date', 'days_diff'])
    crowd_results = []

    for name, group in grouped:
        buy_weight = group[group['decision'] == 'buy']['confidence'].sum()
        sell_weight = group[group['decision'] == 'sell']['confidence'].sum()

        crowd_decision = 'buy' if buy_weight > sell_weight else 'sell'
        crowd_confidence = max(buy_weight, sell_weight) / (buy_weight + sell_weight) * 100 if (buy_weight + sell_weight) > 0 else 50

        actual_sign = group['actual_sign'].iloc[0]
        predicted_sign = 1 if crowd_decision == 'buy' else -1
        is_correct = 1 if predicted_sign == actual_sign else 0
        weighted_score = crowd_confidence if is_correct else -crowd_confidence

        crowd_results.append({
            'symbol': name[0],
            'search_date': name[1],
            'prediction_date': name[2],
            'days_diff': name[3],
            'model_type': 'crowd_aggregate',
            'decision': crowd_decision,
            'confidence': crowd_confidence,
            'predicted_sign': predicted_sign,
            'actual_sign': actual_sign,
            'correct': is_correct,
            'weighted_score': weighted_score,
            'crowd_count': len(group)
        })
    return pd.DataFrame(crowd_results)

df_crowd_agg = aggregate_crowd_predictions(df_merge)
df_expert = df_merge[df_merge['model_type'] == 'expert'].copy()

In [54]:
# -----------------------------
# 8. 평가 1: 단순 정답 유무 채점표
# -----------------------------
print("="*80)
print("[평가 1] 단순 정답 유무 채점표")
print("="*80)

if len(df_expert) > 0:
    print(f"\nExpert 정답률: {df_expert['correct'].mean():.2%} ({df_expert['correct'].sum()}/{len(df_expert)})")
if len(df_crowd_agg) > 0:
    print(f"Crowd 집단지성 정답률: {df_crowd_agg['correct'].mean():.2%} ({df_crowd_agg['correct'].sum()}/{len(df_crowd_agg)})")

# -----------------------------
# 9. 평가 2: 예측일별 집단지성 vs 전문가
# -----------------------------
print("\n" + "="*80)
print("[평가 2] 예측일별 집단지성 vs 전문가 비교")
print("="*80)

prediction_periods = sorted(df_merge['days_diff'].unique())
comparison_results = []

for days in prediction_periods:
    expert_subset = df_expert[df_expert['days_diff'] == days]
    crowd_subset = df_crowd_agg[df_crowd_agg['days_diff'] == days]

    expert_acc = expert_subset['correct'].mean() if len(expert_subset) > 0 else 0
    expert_weighted = expert_subset['weighted_score'].mean() if len(expert_subset) > 0 else 0
    crowd_acc = crowd_subset['correct'].mean() if len(crowd_subset) > 0 else 0
    crowd_weighted = crowd_subset['weighted_score'].mean() if len(crowd_subset) > 0 else 0

    print(f"\n{days}일 후 예측:")
    print(f"  Expert   - 정답률: {expert_acc:.2%}, 가중점수: {expert_weighted:+.2f}")
    print(f"  Crowd    - 정답률: {crowd_acc:.2%}, 가중점수: {crowd_weighted:+.2f}")
    winner = 'Crowd' if crowd_acc > expert_acc else 'Expert' if expert_acc > crowd_acc else '동점'
    print(f"  승자     - {winner}")

    comparison_results.append({
        'days_after': days,
        'expert_accuracy': expert_acc,
        'expert_weighted_score': expert_weighted,
        'crowd_accuracy': crowd_acc,
        'crowd_weighted_score': crowd_weighted,
        'winner_by_accuracy': 'crowd' if crowd_acc > expert_acc else 'expert' if expert_acc > crowd_acc else 'tie'
    })

# -----------------------------
# 10. 평가 3: 종합 점수
# -----------------------------
print("\n" + "="*80)
print("[평가 3] 종합 점수")
print("="*80)

expert_total_acc = df_expert['correct'].mean() if len(df_expert) > 0 else 0
expert_total_weighted = df_expert['weighted_score'].mean() if len(df_expert) > 0 else 0
crowd_total_acc = df_crowd_agg['correct'].mean() if len(df_crowd_agg) > 0 else 0
crowd_total_weighted = df_crowd_agg['weighted_score'].mean() if len(df_crowd_agg) > 0 else 0

print(f"\nExpert 종합")
print(f"  정답률: {expert_total_acc:.2%}")
print(f"  평균 가중점수: {expert_total_weighted:+.2f}")

print(f"\nCrowd 집단지성 종합")
print(f"  정답률: {crowd_total_acc:.2%}")
print(f"  평균 가중점수: {crowd_total_weighted:+.2f}")

print(f"\n최종 승자: ", end="")
if crowd_total_acc > expert_total_acc:
    print("Crowd 집단지성")
elif expert_total_acc > crowd_total_acc:
    print("Expert 전문가")
else:
    print("동점")

================================================================================
[평가 1] 단순 정답 유무 채점표
================================================================================

Expert 정답률: 40.00% (2/5)
Crowd 집단지성 정답률: 60.00% (3/5)

================================================================================
[평가 2] 예측일별 집단지성 vs 전문가 비교
================================================================================

1일 후 예측:
  Expert   - 정답률: 100.00%, 가중점수: +68.00
  Crowd    - 정답률: 100.00%, 가중점수: +100.00
  승자     - 동점

3일 후 예측:
  Expert   - 정답률: 100.00%, 가중점수: +62.00
  Crowd    - 정답률: 100.00%, 가중점수: +100.00
  승자     - 동점

7일 후 예측:
  Expert   - 정답률: 0.00%, 가중점수: -56.00
  Crowd    - 정답률: 100.00%, 가중점수: +67.74
  승자     - Crowd

15일 후 예측:
  Expert   - 정답률: 0.00%, 가중점수: -60.00
  Crowd    - 정답률: 0.00%, 가중점수: -100.00
  승자     - 동점

30일 후 예측:
  Expert   - 정답률: 0.00%, 가중점수: -66.00
  Crowd    - 정답률: 0.00%, 가중점수: -100.00
  승자     - 동점

================================================================================
[평가 3] 종합 점수
================================================================================

Expert 종합
  정답률: 40.00%
  평균 가중점수: -10.40

Crowd 집단지성 종합
  정답률: 60.00%
  평균 가중점수: +13.55

최종 승자: Crowd 집단지성

In [ ]:

# -----------------------------
# 11. 결과 저장
# -----------------------------
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

output_file = f"../data/answer/scoring_results_detailed_{timestamp}.csv"
df_merge.to_csv(output_file, index=False, encoding='utf-8')
print(f"\n상세 결과 저장: {output_file}")

if len(df_crowd_agg) > 0:
    crowd_output = f"../data/answer/scoring_results_crowd_{timestamp}.csv"
    df_crowd_agg.to_csv(crowd_output, index=False, encoding='utf-8')
    print(f"Crowd 집단 결과 저장: {crowd_output}")

comparison_df = pd.DataFrame(comparison_results)
comparison_output = f"../data/answer/scoring_comparison_{timestamp}.csv"
comparison_df.to_csv(comparison_output, index=False, encoding='utf-8')
print(f"예측일별 비교 결과 저장: {comparison_output}")

summary_data = {
    'metric': ['정답률', '평균 가중점수'],
    'expert': [expert_total_acc, expert_total_weighted],
    'crowd': [crowd_total_acc, crowd_total_weighted]
}
summary_df = pd.DataFrame(summary_data)
summary_output = f"../data/answer/scoring_summary_{timestamp}.csv"
summary_df.to_csv(summary_output, index=False, encoding='utf-8')
print(f"종합 요약 저장: {summary_output}")

print("="*80)

In [1]:
import pandas as pd
pd.read_csv('../data/articles/csv/news_with_article_body_test_v1.csv')

      Unnamed: 0  ...                                       article_body
0              0  ...  Adobe CEO Shantanu Narayen speaks during an in...
1              1  ...  Design software maker Adobe Inc. (NASDAQ: ADBE...
2              2  ...  (RTTNews) - Adobe (ADBE) Thursday announced th...
3              3  ...  Analyst Estimates for Q1 FY 2024 Q4 FY 2023 Q1...
4              4  ...                                   No article body.
...          ...  ...                                                ...
1655        1655  ...  Apimeds Pharmaceuticals US, a clinical stage b...
1656        1656  ...  THE COUNT\nButton\nAEG UPS WILKES, HILL IN INT...
1657        1657  ...  Cram Motorsport and US Racing have recently ad...
1658        1658  ...  This story was originally published on Banking...
1659        1659  ...  Sony adds yet another pair of excellent-soundi...

[1660 rows x 16 columns]